### ISSUE TITLE
Positional Audio thinks 3D Sound is disabled

### ISSUE THREAD

**Issue by wilson29thid** [thorwe/CrossTalk#16]
When I open the Positional Audio dialog, it says 3D Sound is Disabled.

![2014031515352037](https://f.cloud.github.com/assets/2887000/2428697/de80d442-ac57-11e3-9c3e-75dd2ad6250f.png)

The only reference to 3D sound I can find is in `Options > Playback > Always set clients 3D positions when available` and it's enabled.

![20140315153534247](https://f.cloud.github.com/assets/2887000/2428698/e2eccdce-ac57-11e3-874c-e152e6f67661.png)

Any idea what's wrong?

**Comment by thorwe** [comment]
closing as it's fixed since ehr, whenever.
