### ISSUE TITLE
Is Radio FX shared with other users even if they don't have CrossTalk installed?

### ISSUE THREAD

**Issue by Flaktrooper500** [thorwe/CrossTalk#21]
Title.

Is it shared? I've just installed Crosstalk, I can hear my friends on TS talking walkietalkie-ish, but they can't hear me the same way if they don't have Crosstalk installed. Is it intended? Or how do I solve this?

In "Radio FX" my checkmark is on Home and Other.

Halp.

**Comment by thorwe** [comment]
That's by design.
With such effects the developer has to make a choice to avoid double applicance of the effect.
There're a couple of more plus points for doing this on receive than send, so that's how it's been done.

**Comment by Flaktrooper500** [comment]
Ah, okay, I thought I was missing something. Thanks for clarification!

**Comment by thorwe** [comment]
No problemo :)
