### ISSUE TITLE
Updater says 1.6.3 is available, only 1.6.2 beta for download

### ISSUE THREAD

**Issue by wohali** [thorwe/CrossTalk#22]
Just like the subject says - the updater is directing me to download a 1.6.3 version, but the main channel is still 1.6.1, and the beta channel only has a 1.6.2 version for download.

Where is the 1.6.3 release?

**Comment by thorwe** [comment]
Hi there,
that's odd, you should've landed over here:
https://github.com/thorwe/CrossTalk/releases

May I ask which url clicking "ok" brought you to (the 1.6.2 page)?

**Comment by wohali** [comment]
The popup window inside of TS itself that tells me an update is available redirects me to:

https://jianji.de/crosstalk/

which then redirects to:

https://jianji.de/index.php/crosstalk/

which has the outdated versions. In fact, the beta is older than the release version on those pages! :(

**Comment by thorwe** [comment]
That beta version is updated now, sorry for the inconvenience.
I had compiled an unreleased beta version inbetween, so it slipped my mind that the live version still links there. Was beginning to wonder why there were no downloads on github ;)

Future updates should link to the latest release of the releases page here on github mentioned above.
