### ISSUE TITLE
CrossTalk for "Vietcong" and "Hidden & Dangerous 2"

### ISSUE THREAD

**Issue by PvtPirate** [thorwe/CrossTalk#26]
Hi, we play Vietcong very often, although it is quite old.
The games IngameVoice is awesome, but in some missions it just breaks, as there are too many ambience sounds.
We just tried using Crosstalk in "Vietcong", but it doesnt recognize the game/player position.
We're going to test the same with "Hidden & Dangerous 2 - Sabre Squadron" soon.
"Ravenshield" didn't work either.
can you add compatibility for those games too?
It seems your method of catching the players position isn't universal.
my brother had the idea of just "listening" for DirectX threads and finding the current camera position and deriving the data from there - independent of which game or application is used.

**Comment by thorwe** [comment]
Sorry for the delay, been at gamescom and rather busy there.

There is indeed no universal method for getting player positions from any game.
I'm implementing mumble link, a standard the game has to support for this to work.
http://wiki.mumble.info/wiki/Games
The list items marked in blue are supported by the manufacturer and CrossTalk, the other items have been reverse engineered and are supported by Mumble exclusively.

It's not in my cards time wise to add individual games by reverse engineering their positional data.
Sorry :(

**Comment by PvtPirate** [comment]
Thanks for the reply.
We made the experience, that in some occassions the plugin doesnt get the player's position in HalfLife2DM, but we couldn't figure out what player actions cause that, except that switching out of the game to change crosstalk settings was involved, because we were trying to find proper values for the "rolloff" and "max distance".

**Comment by zsawyer** [comment]
Hey PvtPirate, good to see you here too. :)

You are best off asking for mumble plugin support at the mumble site. http://forums.mumble.info/viewforum.php?f=2
Imho this issue should be closed as wont-fix. 

As a hint for others that might stumble upon this thread here is a list of games supported by mumble-link and therefore by this awesome TS-plugin: http://wiki.mumble.info/wiki/Games

For the ones eager enough to get things going themselves here is a starting point: http://wiki.mumble.info/wiki/Pluginguide


On a side note: Please open a separate ticket for unrelated issues. It helps keep things organized.

**Comment by PvtPirate** [comment]
thanks zsawyer, we'll try building a mumbleplugin for vietcong. i hope it works to install that to teamspeak/crosstalk.
(Offtopic @zsawyer: As far as i've seen, your mumble-mod works good in MineCraft with Crosstalk.
but i couldnt convince my self of using the outdated MC version 1.8 longer than necessary for testing.)

**Comment by thorwe** [comment]
Note that if you/someone does it like the minecraft mod does, so either as some sort of plugin for your game or as independent app that grabs the positional data and implements the mumble link protocol, that's the way to hit two targets (mumble + ts/crosstalk) with one.

I'll mark this invalid instead, makes me look less lazy! ;)
Have a nice weekend
