### ISSUE TITLE
Switch'n'Talk not working on Windows 10

### ISSUE THREAD

**Issue by nefastu** [thorwe/CrossTalk#29]
Hey,

after switching from Windows 7 to Windows 10 my Switch'n'Talk hotkeys are not working anymore.
It seems like the plugin command 'Next Tab and Talk Start' starts on key up, even if it is configured to start on key down, resulting in continuous transmission after pressing the hotkey.

TS3-Version: 3.0.18.1
Crosstalk-Version: 1.6.3.090501

This could also be an issue on Windows 8 / 8.1, as some friends on these OS versions reported similar issues with Switch'n'Talk.

**Comment by thorwe** [comment]
I can reproduce this, will see what I can do.

**Comment by thorwe** [comment]
Fix will roll out with the next update on the beta channel, which is planned for sometime around the weekend.

Thanks for the report :)

**Comment by thorwe** [comment]
bandaid for TS3 bug in https://github.com/thorwe/CrossTalk/releases/tag/v1.6.3.102001-beta
