### ISSUE TITLE
Distance attenuation is working in reverse

### ISSUE THREAD

**Issue by hendrikp** [thorwe/CrossTalk#32]
The distance attenuation is actually getting louder the further i go away from the source. Seems its working in reverse.

My settings: https://gyazo.com/58b434146eed4069e5c0d9e10364b0a7

**Comment by thorwe** [comment]
Make sure you use the latest version here from the releases page: https://github.com/thorwe/CrossTalk/releases
The version on the official teamspeak addon page is heavily outdated.

**Comment by hendrikp** [comment]
Ok i used 1.6.1 on both sides, will try with latest and report back.

**Comment by Virtualistik** [comment]
Is your Rolloff value positive? It should be negative in order to decrease when you move further apart.

**Comment by Bluscream** [comment]
@thorwe why?

**Comment by thorwe** [comment]
Why what? Note my comment in this issue is from a year ago if you mean that.

**Comment by Bluscream** [comment]
Ohh okay i thought they wouldn't accept updates once again ;D

**Comment by thorwe** [comment]
Closing as solved.
