### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by Brezz51ST** [thorwe/CrossTalk#35]
I download it, then when i put it into plugins folder of ts3 client but when i open ts3 i cant find it in plugins, please help.

**Comment by thorwe** [comment]
The file that's downloaded is an installation package containing the plugin. Double clicking it should start the client's addon installer, which then extracts the files.

**Comment by thorwe** [comment]
Closing as solved - plugin should be installed from within the TeamSpeak client for automatic updates from 3.1 onwards.
