### ISSUE TITLE
Support API version 21

### ISSUE THREAD

**Issue by Nothing4You** [thorwe/CrossTalk#36]
Hey there,

the current TS3 beta is using the a new API version 21.

It doesn't seem like there is an SDK available yet for version 21, however, please add support for this as soon as possible.

**Comment by Nothing4You** [comment]
http://dl.4players.de/ts/client/pluginsdk/pluginsdk_3.1.zip seems to be the SDK for version 21.

**Comment by thorwe** [comment]
Hi, I'm aware.
The update will be found on the upcoming addon system of TeamSpeak 3.1.

**Comment by wohali** [comment]
Hi @thorwe, any update on support for TS 3.1 Beta? It's starting to be advertised in the scroll on the bottom of the 3.0 client, and I've had to advise my users for now to avoid the beta until Crosstalk is updated.

**Comment by RacerXx** [comment]
Could you provide details on how to build the plugin for use in 3.1 beta?

**Comment by Bluscream** [comment]
@wohali https://github.com/thorwe/CrossTalk/blob/gh-pages/src/plugin.cpp#L81

**Comment by zo04** [comment]
@Bluscream 

How does this answer the question?

**Comment by thorwe** [comment]
Hopefully I can get it done over christmas vacation.
As this update comes together with a split into several plugins for better maintainability, it's a bit more to do than just upping the api version - and I don't want to add the non-splitted variant to the store with such a limited life time.

**Comment by enzoleecamper** [comment]
Some news thorwe? 
Waiting for it very long, hate to play without cross talk on Arma 3 Altis life ^^

**Comment by Bluscream** [comment]
API 21 is out of beta so it's time to release a update!

**Comment by thorwe** [comment]
I'm deeply aware of that ;P

**Comment by Bluscream** [comment]
If this whole qt crap would work for me, I would try my best to atleast update the API version.

**Comment by RacerXx** [comment]
Dude! you guys need to chill. Pestering the guy aint going to make him go any faster or release any sooner. I mean how many differences could there be in the new vs old api? 30 minutes to make a correction or two to the code and about 30 secs to rebuild it. Find another plugin....move on

**Comment by Bluscream** [comment]
The required Qt configuration doesn't work for everyone. Otherwise I would have made a in 2015

**Comment by DSDV** [comment]
So since TS3 3.1 hast 21 API and there is no workaround so far for using old plugins with API20 is there a release plan for crosstalk which uses API21?

**Comment by RacerXx** [comment]
need to stop worrying about splitting it up. It needs a quick build with latest API so all these people dependent on the plugin have something to use in the meantime. It can be split afterwords. How hard can it be to release a quick build for these people? Why keep stringing these people and their users waiting since before xmas along to do a 30 minute rebuild and git push? Support your work and your followers man geez!!! Unsubscribing fuck this project

**Comment by thorwe** [comment]
The radio effects should be there before next week, unless unforeseen circumstances.
The crashes _sort of_ reported by users in that module should be fixed now.
Issues remaining are some problem with initial settings resulting in silence and an issue with the channel ui not sizing properly due to some Qt 5.6.1 shennanigans.
In reference to that deleted rage post, that'll be done in 30 minutes _max_, postponing lower priority issues like taking care of the effects of having moved, as in get a real bed, a washer, a fridge, a car, plus make a living and have a life.
I do take requests for the priority though, i.e. what besides radio effects are most wanted here.

**Comment by DSDV** [comment]
My personal most wanted funtion is the "Stereo Position Spread" !
its horrible when multiple persons talk without 3D audio ;)

btw i realy aprecciate your work!  <3

**Comment by wohali** [comment]
HI @thorwe , as always I'm looking for the Client Group Whisper System functionality, along with the Radio FX stuff.

**Comment by zsawyer** [comment]
Further support of Mumble 3D Positioning convention. 
I am getting good feedback when directing Minecraft players to CrossTalk as a TS3 alternative to Mumble for the game-based Positional Audio with my mod. They really enjoy CrossTalk and seems to work great.

**Comment by thorwe** [comment]
Bad news is, I didn't make the deadline.
Good news is, the remaining issues with the radio fx are solved, it will be up tomorrow-ish from inside the client. I'll do a follow-up post once it's publicly available there.
On to the rest.

**Comment by thorwe** [comment]
RadioFX plugin is now available.
Please install from inside the client (this enables automatic updates).
You can find it in the client options (alt-p)->Addons->Browse Online.

**Comment by KantiOM** [comment]
I installed your RadioFX, and team speak crashes whenever someone speaking in chanel, even if it set only to whisper.
(sorry it's kinda offtop)

**Comment by wohali** [comment]
Hi @thorwe , any more progress to share? ;)

**Comment by thorwe** [comment]
Download for the remaining functionality will be available shortly, i.e. before the next weekend.
No progress the RadioFx crash ( https://github.com/thorwe/CrossTalk/issues/41 ) on talk status changes, as I cannot replicate it no matter what.

**Comment by thorwe** [comment]
The [Ducker is up](https://www.myteamspeak.com/addons/d7dd6029-6941-4690-9ebb-c7f793e00a0e). CrossTalk is under review.

**Comment by thorwe** [comment]
And finally, CrossTalk is up, too.
Please install from within the client to enable automatic updates.
Still hunting a crash on talk status change report for RadioFX, might be happening with the other ones, too due to partially shared code base.

Apologies for the delay.

**Comment by Bluscream** [comment]
Awesome work @thorwe 👍 It's great to see Teamspeak Devs that still take enough spare time to manage their plugins <3

**Comment by henryspike** [comment]
Hey! I still cant find the 'Radio FX'. When I click on the Plugins->CrossTalk , I only find Positional Spread, Positional Audio and GW2 Map but cant find the Radio FX

**Comment by thorwe** [comment]
RadioFx and the Ducker are standalone addons now. Search for RadioFx in the client's addon browser to install.

**Comment by thorwe** [comment]
Closing as solved.
