### ISSUE TITLE
TS3 Plugin API version 21 not supported?

### ISSUE THREAD

**Issue by DSDV** [thorwe/CrossTalk#40]
Hello Guys,
since latest updates to the Teamspeak Client the addon is disabled due to the fact that it dindt support the newest version of the addon API? 

is there a workaround or fix for that problem?

with best +DS_DV+

PS: sorry for my bad english

**Comment by Bluscream** [comment]
Duplicate of #36

**Comment by DSDV** [comment]
sorry

**Comment by Bluscream** [comment]
Please close your issue and comment on the original one instead :)
