### ISSUE TITLE
Radio FX crashing TeamSpeak

### ISSUE THREAD

**Issue by KantiOM** [thorwe/CrossTalk#41]
When plugin activated and someone start talking, it's crashing my TS. At first it happend when I activate plugin in the middle of a talk, now it's happening all the time when people start talking.

**Comment by thorwe** [comment]
Hm ok, couldn't replicate this (ofc I tested basic functionality).
Any chance you could up the crashdump file somewhere for me? (%appdata%/TS3client/)

**Comment by KantiOM** [comment]
[ts3dump_1485809726310.zip](https://github.com/thorwe/CrossTalk/files/740256/ts3dump_1485809726310.zip)
[ts3dump_1485809659853.zip](https://github.com/thorwe/CrossTalk/files/740257/ts3dump_1485809659853.zip)
[ts3dump_1485809560213.zip](https://github.com/thorwe/CrossTalk/files/740259/ts3dump_1485809560213.zip)
I noticed that now it don't crash TS when i connect to server with already activated plugin, but when i reload it, it crashes

**Comment by thorwe** [comment]
Well, I found and fixed one crash that's triggered if the Radio FX ui is open when disabling or reloading the plugin. Doesn't appear to fit the initial description though, there should be some bugger on talk status changes, too.

**Comment by Bluscream** [comment]
@KantiOM also check which other plugins you have enabled. Sometimes plugin combinations cause crashes.

**Comment by KantiOM** [comment]
@Bluscream all other plugins disabled, also I restared TS after doing it. So only RadioFX working, and still crashing.

**Comment by thorwe** [comment]
An update for RadioFX is now up and should be automatically installed if the addon was installed from within the client.
Not entirely sure if it fixes the issue, however fixes an issue.
