### ISSUE TITLE
Missing DLL

### ISSUE THREAD

**Issue by mackenziexD** [thorwe/CrossTalk#43]
Screenshot: http://image.prntscr.com/image/334f9c0935034cacab0a867804db3fce.png

```The procedure entry point could not be located as a dnamic link libary Teamspeak 3 Client\plugins\cross_talk_win64.dll```

with a install from teamspeak using the installer on Teamspeak version: 3.0.19.4

**Comment by thorwe** [comment]
Plugins on myteamspeak.com are exclusively for Client version 3.1+.
For the old client, you can use the ones from here: https://github.com/thorwe/CrossTalk/releases
However, only the version on myteamspeak (3.1+) will receive further updates.

**Comment by thorwe** [comment]
Closing as presumably solved.
