### ISSUE TITLE
Radio FX and Ducking are missing

### ISSUE THREAD

**Issue by Joel6909** [thorwe/CrossTalk#44]
So, apparently when I download the plugin I'm supposed to have the following options: Position Spread, Position Audio, Gw2 Map, Radio FX and Ducking but instead only Position Spread, Position Audio and Gw2 Map show up.

**Comment by Bluscream** [comment]
Its split up into multiple plugins, search again :)

**Comment by thorwe** [comment]
At last, descriptions and all that are updated. At the time of this writing there's "CrossTalk", "RadioFX" and "Ducker" installable from directly within the client. Closing as solved.
