### ISSUE TITLE
Ducking option not available

### ISSUE THREAD

**Issue by darkwyrm88** [thorwe/CrossTalk#48]
This plugin advertises its Channel Ducking capabilities, but this option does not appear to be available when the plugin is installed on an up-to-date version of TeamSpeak.

**Comment by darkwyrm88** [comment]
![screenshot 2018-08-27 13 19 22](https://user-images.githubusercontent.com/1761823/44683733-fa897d00-a9fb-11e8-9a4d-0193228cd59e.png)

**Comment by thorwe** [comment]
https://www.myteamspeak.com/addons/d7dd6029-6941-4690-9ebb-c7f793e00a0e
https://github.com/thorwe/teamspeak-plugin-ducker
Ducking became its own plugin.
