### ISSUE TITLE
API version 23 support

### ISSUE THREAD

**Issue by nefastu** [thorwe/CrossTalk#51]
Hey there,

the current TS3 client (v3.3.0) requires plugins on API version 23 as minimum.

I'd love to see an update for CrossTalk, so please update the referenced API if possible. :)

**Comment by thorwe** [comment]
Coming soon.

**Comment by tkirl** [comment]
Looking forward to that! Teamspeak without CrossTalk is no fun at all. :-(

**Comment by nthnwllms** [comment]
Any idea when we'll get CrossTalk updated to api v23? I know we got RadioFX some time ago and you said soon almost 2 months ago 😥

**Comment by jdsemma** [comment]
Time passes... still no crosstalk?? Sadface

**Comment by thorwe** [comment]
It's pending on myteamspeak now. Sorry for the delay.

**Comment by thorwe** [comment]
...and up
