### ISSUE TITLE
Add a proper license

### ISSUE THREAD

**Issue by Atemu** [thorwe/CrossTalk#61]
Hi, I'm currently building out TS3 plugin packaging infrastructure for Nixpkgs (https://github.com/NixOS/nixpkgs/pull/305852) and CrossTalk is one of the plugins I'd like to package. 

To get it to build on a modern Linux, I needed to write some patches (https://github.com/thorwe/CrossTalk/pull/60) whereby I noticed that this project doesn't have a license. This is a bit of a problem because I'm technically not allowed to touch the code (your copyright). AFAIUI publishing it on GH does grant an implicit license to collaborate in this manner but it's entirely unclear whether end-users would be allowed to compile the code for the purpose of using it though, so packaging isn't an option.

I'd much rather the license was explicit in any case.

While I'd prefer a free open source license such as MIT or Apache-2.0 or even copyleft (LGPL, can't do full GPL in this case), an unfree license such as CC-BY-NC would be fine too as long as the terms are clear. I'd personally choose the LGPL but it's your choice of course.

(Please make sure to also apply the license to https://github.com/thorwe/teamspeak-plugin-qt-common and perhaps your other plugins too.)

***

Danke übrigens dass du dieses Plugin gebaut hast und hier publizierst :)

**Comment by thorwe** [comment]
Sorry for the delay.

**Comment by Atemu** [comment]
Fixed in https://github.com/thorwe/CrossTalk/commit/a1765120990b54ede6c83b992303ed35779884c1, thank you!
